### ISSUE TITLE
ALLOWED_EXTS allows pngs & jpgs

### ISSUE THREAD

**Issue by MichaelHillcox** [DaveM2011/dispatch-zep#4]
Dont think it's working :P

**Comment by MichaelHillcox** [comment]
@DaveM2011 This looks like it's fixed now but when you try to upload them the system will say 100% 0 / 0 btyes. Think you need to reject the upload sooner? or fix the UI back to it's original state :)

**Comment by DaveM2011** [comment]
na im going to diplay an error and also add a js ext checker
